### ISSUE TITLE
On Linux Mint, when Helo is closed. It keeps on running but becomes invisible (unable to ALT-TAB)

### ISSUE THREAD

**Issue by eugenevdm** [beyondcode/helo-community#55] opened 2021-01-14 02:42 UTC
On my stock Linux Mint 20 desktop, when I have Helo 1.3.0 running, it works perfectly.

If I close it, it keeps on running.

I know it keeps on running because when I send SMTP through port 2525 I see the notifications.

However, I cannot see the Helo application anymore. It's gone, away from the task list, with no way to see the UI anymore.

If I start it up again, another instance starts up, and I can't see any new emails. I still get notifications. 
Like there are now two running with first one behind the scenes in the background.

The only resolution I have is to reboot my workstation, and to try and remember to never close Helo. Happy if you want to Anydesk to my computer.

**Comment by sschlein** [comment] 2021-01-14 09:22
I think this is a duplicate of https://github.com/beyondcode/helo-community/issues/52

We are going to work on an update that finally addresses this issue very soon. I am sorry for the inconvenience at the moment.

**Closed by sschlein** 2021-01-14 09:22 UTC
